name: Grading Workflow - Assignment 6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Or your desired version

    # Commenting out the external test download since we're using local tests
    # - name: Download latest test files
    #   run: |
    #     # Create the target directory if it doesn't exist
    #     mkdir -p .github/tests
    #     # Download from the correct assignment repository (updated to 5)
    #     # Download the test script as test_assignment.py
    #     curl -o .github/tests/test_assignment.py https://raw.githubusercontent.com/UCSF-DataSci/datasci223_assignment6/main/.github/tests/test_assignment.py
    #     # Download the consolidated requirements file as requirements.txt
    #     curl -o .github/tests/requirements.txt https://raw.githubusercontent.com/UCSF-DataSci/datasci223_assignment6/main/.github/tests/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install required packages for tests
        pip install pytest numpy pandas matplotlib scikit-learn tensorflow ipykernel

    - name: Setup Jupyter Kernel
      run: |
        python -m ipykernel install --user --name=python3 --display-name="Python 3"

    - name: Run tests
      run: |
        # Use our local tests instead of downloaded ones
        pytest tests/test_assignment6.py -v